/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "recursive_modules.v:184.1-213.10" *)
module accumulator_l7(clk, rst, a, b, acc);
  reg \$auto$verilog_backend.cc:2184:dump_module$30  = 0;
  (* src = "recursive_modules.v:205.5-210.8" *)
  reg [8:0] _0_;
  (* src = "recursive_modules.v:197.25-197.41" *)
  wire [7:0] _1_;
  (* src = "recursive_modules.v:196.25-196.41" *)
  wire [7:0] _2_;
  (* src = "recursive_modules.v:187.18-187.19" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "recursive_modules.v:189.18-189.21" *)
  output [8:0] acc;
  wire [8:0] acc;
  (* src = "recursive_modules.v:191.16-191.23" *)
  reg [8:0] acc_reg;
  (* src = "recursive_modules.v:188.18-188.19" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "recursive_modules.v:185.18-185.21" *)
  input clk;
  wire clk;
  (* src = "recursive_modules.v:193.16-193.26" *)
  wire [7:0] feedback_a;
  (* src = "recursive_modules.v:194.16-194.26" *)
  wire [7:0] feedback_b;
  (* src = "recursive_modules.v:192.16-192.23" *)
  wire [8:0] new_sum;
  (* src = "recursive_modules.v:186.18-186.21" *)
  input rst;
  wire rst;
  assign _1_ = acc_reg[7:0] & (* src = "recursive_modules.v:197.25-197.41" *) b;
  assign _2_ = acc_reg[7:0] ^ (* src = "recursive_modules.v:196.25-196.41" *) a;
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:199.14-203.6" *)
  adder_l6 u_l6 (
    .a(feedback_a),
    .b(feedback_b),
    .sum(new_sum)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$30 ) begin end
    _0_ = acc_reg;
    (* src = "recursive_modules.v:206.9-209.32" *)
    casez (rst)
      /* src = "recursive_modules.v:206.13-206.16" */
      1'h1:
          _0_ = 9'h000;
      /* src = "recursive_modules.v:208.9-208.13" */
      default:
          _0_ = new_sum;
    endcase
  end
  always @(posedge clk) begin
      acc_reg <= _0_;
  end
  always @(posedge rst) begin
      acc_reg <= _0_;
  end
  assign feedback_a = _2_;
  assign feedback_b = _1_;
  assign acc = acc_reg;
endmodule

(* src = "recursive_modules.v:8.1-19.10" *)
module adder_l0(a, b, sum);
  (* src = "recursive_modules.v:18.18-18.63" *)
  wire [4:0] _0_;
  (* src = "recursive_modules.v:17.29-17.34" *)
  wire [3:0] _1_;
  (* src = "recursive_modules.v:16.29-16.34" *)
  wire [3:0] _2_;
  (* src = "recursive_modules.v:9.18-9.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "recursive_modules.v:10.18-10.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "recursive_modules.v:14.16-14.30" *)
  wire [3:0] internal_carry;
  (* src = "recursive_modules.v:13.16-13.28" *)
  wire [3:0] internal_xor;
  (* src = "recursive_modules.v:11.18-11.21" *)
  output [4:0] sum;
  wire [4:0] sum;
  assign _0_ = { 1'h0, internal_xor } + (* src = "recursive_modules.v:18.18-18.63" *) { 1'h0, internal_carry };
  assign _1_ = a & (* src = "recursive_modules.v:17.29-17.34" *) b;
  assign _2_ = a ^ (* src = "recursive_modules.v:16.29-16.34" *) b;
  assign internal_xor = _2_;
  assign internal_carry = _1_;
  assign sum = _0_;
endmodule

(* src = "recursive_modules.v:22.1-42.10" *)
module adder_l1(a, b, sum);
  (* src = "recursive_modules.v:41.18-41.50" *)
  wire [4:0] _0_;
  (* src = "recursive_modules.v:31.20-31.31" *)
  wire [3:0] _1_;
  (* src = "recursive_modules.v:32.20-32.31" *)
  wire [3:0] _2_;
  (* src = "recursive_modules.v:23.18-23.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "recursive_modules.v:24.18-24.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "recursive_modules.v:29.17-29.31" *)
  wire carry_feedback;
  (* src = "recursive_modules.v:27.17-27.22" *)
  wire [3:0] pre_a;
  (* src = "recursive_modules.v:27.24-27.29" *)
  wire [3:0] pre_b;
  (* src = "recursive_modules.v:28.17-28.24" *)
  wire [4:0] sub_sum;
  (* src = "recursive_modules.v:25.18-25.21" *)
  output [4:0] sum;
  wire [4:0] sum;
  assign _0_ = sub_sum + (* src = "recursive_modules.v:41.18-41.50" *) { 4'h0, carry_feedback };
  assign _1_ = a ^ (* src = "recursive_modules.v:31.20-31.31" *) 4'h1;
  assign _2_ = b ^ (* src = "recursive_modules.v:32.20-32.31" *) 4'h2;
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:34.14-38.6" *)
  adder_l0 u_l0 (
    .a(pre_a),
    .b(pre_b),
    .sum(sub_sum)
  );
  assign pre_a = _1_;
  assign pre_b = _2_;
  assign carry_feedback = sub_sum[4];
  assign sum = _0_;
endmodule

(* src = "recursive_modules.v:45.1-65.10" *)
module adder_l2(a, b, sum);
  (* src = "recursive_modules.v:54.23-54.31" *)
  wire [3:0] _0_;
  (* src = "recursive_modules.v:55.23-55.31" *)
  wire [3:0] _1_;
  (* src = "recursive_modules.v:63.23-63.41" *)
  wire [4:0] _2_;
  (* src = "recursive_modules.v:46.18-46.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "recursive_modules.v:52.16-52.24" *)
  wire [4:0] adjusted;
  (* src = "recursive_modules.v:47.18-47.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "recursive_modules.v:50.16-50.24" *)
  wire [3:0] masked_a;
  (* src = "recursive_modules.v:50.26-50.34" *)
  wire [3:0] masked_b;
  (* src = "recursive_modules.v:51.16-51.23" *)
  wire [4:0] partial;
  (* src = "recursive_modules.v:48.18-48.21" *)
  output [4:0] sum;
  wire [4:0] sum;
  assign _0_ = a & (* src = "recursive_modules.v:54.23-54.31" *) 4'hf;
  assign _1_ = b & (* src = "recursive_modules.v:55.23-55.31" *) 4'hf;
  assign _2_ = partial ^ (* src = "recursive_modules.v:63.23-63.41" *) 5'h03;
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:57.14-61.6" *)
  adder_l1 u_l1 (
    .a(masked_a),
    .b(masked_b),
    .sum(partial)
  );
  assign masked_a = _0_;
  assign masked_b = _1_;
  assign adjusted = _2_;
  assign sum = adjusted;
endmodule

(* src = "recursive_modules.v:68.1-95.10" *)
module adder_l3(a, b, sum);
  (* src = "recursive_modules.v:78.20-78.26" *)
  wire [3:0] _0_;
  (* src = "recursive_modules.v:77.20-77.26" *)
  wire [3:0] _1_;
  (* src = "recursive_modules.v:93.23-93.36" *)
  wire [4:0] _2_;
  (* src = "recursive_modules.v:69.18-69.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "recursive_modules.v:73.16-73.21" *)
  wire [3:0] a_reg;
  (* src = "recursive_modules.v:70.18-70.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "recursive_modules.v:73.23-73.28" *)
  wire [3:0] b_reg;
  (* src = "recursive_modules.v:75.16-75.24" *)
  wire [4:0] combined;
  (* src = "recursive_modules.v:74.16-74.21" *)
  wire [4:0] out_a;
  (* src = "recursive_modules.v:74.23-74.28" *)
  wire [4:0] out_b;
  (* src = "recursive_modules.v:71.18-71.21" *)
  output [4:0] sum;
  wire [4:0] sum;
  assign _0_ = b << (* src = "recursive_modules.v:78.20-78.26" *) 32'd1;
  assign _1_ = a >> (* src = "recursive_modules.v:77.20-77.26" *) 32'd1;
  assign _2_ = out_a ^ (* src = "recursive_modules.v:93.23-93.36" *) out_b;
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:81.14-85.6" *)
  adder_l2 u_l2_a (
    .a(a),
    .b(a_reg),
    .sum(out_a)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:87.14-91.6" *)
  adder_l2 u_l2_b (
    .a(b),
    .b(b_reg),
    .sum(out_b)
  );
  assign a_reg = _1_;
  assign b_reg = _0_;
  assign combined = _2_;
  assign sum = combined;
endmodule

(* src = "recursive_modules.v:98.1-133.10" *)
module adder_l4(a, b, sum);
  (* src = "recursive_modules.v:124.23-124.40" *)
  wire [3:0] _00_;
  (* src = "recursive_modules.v:109.17-109.28" *)
  wire [3:0] _01_;
  (* src = "recursive_modules.v:110.17-110.28" *)
  wire [3:0] _02_;
  (* src = "recursive_modules.v:128.15-128.20" *)
  wire [3:0] _03_;
  (* src = "recursive_modules.v:132.18-132.25" *)
  wire [4:0] _04_;
  (* src = "recursive_modules.v:132.18-132.30" *)
  wire [4:0] _05_;
  (* src = "recursive_modules.v:99.18-99.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "recursive_modules.v:103.16-103.18" *)
  wire [3:0] a0;
  (* src = "recursive_modules.v:103.20-103.22" *)
  wire [3:0] a1;
  (* src = "recursive_modules.v:100.18-100.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "recursive_modules.v:103.24-103.26" *)
  wire [3:0] b0;
  (* src = "recursive_modules.v:103.28-103.30" *)
  wire [3:0] b1;
  (* src = "recursive_modules.v:105.16-105.24" *)
  wire [3:0] feedback;
  (* src = "recursive_modules.v:104.16-104.18" *)
  wire [4:0] s0;
  (* src = "recursive_modules.v:104.20-104.22" *)
  wire [4:0] s1;
  (* src = "recursive_modules.v:104.24-104.26" *)
  wire [4:0] s2;
  (* src = "recursive_modules.v:101.18-101.21" *)
  output [4:0] sum;
  wire [4:0] sum;
  assign _00_ = s0[3:0] & (* src = "recursive_modules.v:124.23-124.40" *) s1[3:0];
  assign _01_ = a ^ (* src = "recursive_modules.v:109.17-109.28" *) 4'ha;
  assign _02_ = b ^ (* src = "recursive_modules.v:110.17-110.28" *) 4'h5;
  assign _03_ = a ^ (* src = "recursive_modules.v:128.15-128.20" *) b;
  assign _04_ = s0 ^ (* src = "recursive_modules.v:132.18-132.25" *) s1;
  assign _05_ = _04_ ^ (* src = "recursive_modules.v:132.18-132.30" *) s2;
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:112.14-116.6" *)
  adder_l3 u_l3_0 (
    .a(a0),
    .b(b0),
    .sum(s0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:118.14-122.6" *)
  adder_l3 u_l3_1 (
    .a(a1),
    .b(b1),
    .sum(s1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:126.14-130.6" *)
  adder_l3 u_l3_2 (
    .a(feedback),
    .b(_03_),
    .sum(s2)
  );
  assign a0 = a;
  assign b0 = b;
  assign a1 = _01_;
  assign b1 = _02_;
  assign feedback = _00_;
  assign sum = _05_;
endmodule

(* src = "recursive_modules.v:136.1-154.10" *)
module adder_l5(a, b, sum);
  (* src = "recursive_modules.v:148.18-148.43" *)
  wire [3:0] _0_;
  (* src = "recursive_modules.v:147.18-147.43" *)
  wire [3:0] _1_;
  (* src = "recursive_modules.v:153.18-153.33" *)
  wire [4:0] _2_;
  (* src = "recursive_modules.v:137.18-137.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "recursive_modules.v:138.18-138.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "recursive_modules.v:142.16-142.19" *)
  wire [3:0] fb0;
  (* src = "recursive_modules.v:142.21-142.24" *)
  wire [3:0] fb1;
  (* src = "recursive_modules.v:141.16-141.22" *)
  wire [4:0] stage0;
  (* src = "recursive_modules.v:141.24-141.30" *)
  wire [4:0] stage1;
  (* src = "recursive_modules.v:141.32-141.38" *)
  wire [4:0] stage2;
  (* src = "recursive_modules.v:141.40-141.46" *)
  wire [4:0] stage3;
  (* src = "recursive_modules.v:139.18-139.21" *)
  output [4:0] sum;
  wire [4:0] sum;
  assign _0_ = stage0[3:0] & (* src = "recursive_modules.v:148.18-148.43" *) stage1[3:0];
  assign _1_ = stage0[3:0] ^ (* src = "recursive_modules.v:147.18-147.43" *) stage1[3:0];
  assign _2_ = stage2 ^ (* src = "recursive_modules.v:153.18-153.33" *) stage3;
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:144.14-144.53" *)
  adder_l4 u_l4_0 (
    .a(a),
    .b(b),
    .sum(stage0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:145.14-145.53" *)
  adder_l4 u_l4_1 (
    .a(b),
    .b(a),
    .sum(stage1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:150.14-150.53" *)
  adder_l4 u_l4_2 (
    .a(fb0),
    .b(fb1),
    .sum(stage2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:151.14-151.53" *)
  adder_l4 u_l4_3 (
    .a(fb1),
    .b(fb0),
    .sum(stage3)
  );
  assign fb0 = _1_;
  assign fb1 = _0_;
  assign sum = _2_;
endmodule

(* src = "recursive_modules.v:157.1-181.10" *)
module adder_l6(a, b, sum);
  (* src = "recursive_modules.v:179.23-179.48" *)
  wire [4:0] _0_;
  (* src = "recursive_modules.v:158.18-158.19" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "recursive_modules.v:159.18-159.19" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "recursive_modules.v:163.16-163.24" *)
  wire [3:0] carry_in;
  (* src = "recursive_modules.v:162.24-162.30" *)
  wire [4:0] hi_sum;
  (* src = "recursive_modules.v:162.16-162.22" *)
  wire [4:0] lo_sum;
  (* src = "recursive_modules.v:164.16-164.21" *)
  wire [4:0] merge;
  (* src = "recursive_modules.v:160.18-160.21" *)
  output [8:0] sum;
  wire [8:0] sum;
  assign _0_ = hi_sum + (* src = "recursive_modules.v:179.23-179.48" *) { 1'h0, carry_in };
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:172.14-176.6" *)
  adder_l5 u_hi (
    .a(a[7:4]),
    .b(b[7:4]),
    .sum(hi_sum)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:166.14-170.6" *)
  adder_l5 u_lo (
    .a(a[3:0]),
    .b(b[3:0]),
    .sum(lo_sum)
  );
  assign carry_in = { 3'h0, lo_sum[4] };
  assign merge = _0_;
  assign sum = { merge, lo_sum[3:0] };
endmodule

(* src = "recursive_modules.v:216.1-250.10" *)
module dual_channel_l8(clk, rst, a0, b0, a1, b1, acc0, acc1, combined);
  (* src = "recursive_modules.v:244.22-244.39" *)
  wire [8:0] _0_;
  (* src = "recursive_modules.v:245.22-245.39" *)
  wire [8:0] _1_;
  (* src = "recursive_modules.v:249.23-249.40" *)
  wire [8:0] _2_;
  (* src = "recursive_modules.v:219.18-219.20" *)
  input [7:0] a0;
  wire [7:0] a0;
  (* src = "recursive_modules.v:220.18-220.20" *)
  input [7:0] a1;
  wire [7:0] a1;
  (* src = "recursive_modules.v:221.18-221.22" *)
  output [8:0] acc0;
  wire [8:0] acc0;
  (* src = "recursive_modules.v:222.18-222.22" *)
  output [8:0] acc1;
  wire [8:0] acc1;
  (* src = "recursive_modules.v:219.22-219.24" *)
  input [7:0] b0;
  wire [7:0] b0;
  (* src = "recursive_modules.v:220.22-220.24" *)
  input [7:0] b1;
  wire [7:0] b1;
  (* src = "recursive_modules.v:217.18-217.21" *)
  input clk;
  wire clk;
  (* src = "recursive_modules.v:223.18-223.26" *)
  output [8:0] combined;
  wire [8:0] combined;
  (* src = "recursive_modules.v:226.16-226.23" *)
  wire [8:0] cross_a;
  (* src = "recursive_modules.v:226.25-226.32" *)
  wire [8:0] cross_b;
  (* src = "recursive_modules.v:225.16-225.20" *)
  wire [8:0] raw0;
  (* src = "recursive_modules.v:225.22-225.26" *)
  wire [8:0] raw1;
  (* src = "recursive_modules.v:218.18-218.21" *)
  input rst;
  wire rst;
  assign _0_ = raw0 ^ (* src = "recursive_modules.v:244.22-244.39" *) { 1'h0, a1 };
  assign _1_ = raw1 ^ (* src = "recursive_modules.v:245.22-245.39" *) { 1'h0, b0 };
  assign _2_ = cross_a ^ (* src = "recursive_modules.v:249.23-249.40" *) cross_b;
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:228.20-234.6" *)
  accumulator_l7 u_ch0 (
    .a(a0),
    .acc(raw0),
    .b(b0),
    .clk(clk),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:236.20-242.6" *)
  accumulator_l7 u_ch1 (
    .a(a1),
    .acc(raw1),
    .b(b1),
    .clk(clk),
    .rst(rst)
  );
  assign cross_a = _0_;
  assign cross_b = _1_;
  assign acc0 = raw0;
  assign acc1 = raw1;
  assign combined = _2_;
endmodule

(* top =  1  *)
(* src = "recursive_modules.v:253.1-290.10" *)
module top_recursive(clk, rst, in_a, in_b, result, stage0_acc0, stage0_acc1, stage0_combined, stage1_acc0, stage1_acc1, stage1_combined);
  (* src = "recursive_modules.v:289.21-289.54" *)
  wire [8:0] _0_;
  (* src = "recursive_modules.v:254.18-254.21" *)
  input clk;
  wire clk;
  (* src = "recursive_modules.v:256.18-256.22" *)
  input [7:0] in_a;
  wire [7:0] in_a;
  (* src = "recursive_modules.v:257.18-257.22" *)
  input [7:0] in_b;
  wire [7:0] in_b;
  (* src = "recursive_modules.v:258.18-258.24" *)
  output [8:0] result;
  wire [8:0] result;
  (* src = "recursive_modules.v:255.18-255.21" *)
  input rst;
  wire rst;
  (* src = "recursive_modules.v:260.16-260.27" *)
  output [8:0] stage0_acc0;
  wire [8:0] stage0_acc0;
  (* src = "recursive_modules.v:260.29-260.40" *)
  output [8:0] stage0_acc1;
  wire [8:0] stage0_acc1;
  (* src = "recursive_modules.v:260.42-260.57" *)
  output [8:0] stage0_combined;
  wire [8:0] stage0_combined;
  (* src = "recursive_modules.v:261.16-261.27" *)
  output [8:0] stage1_acc0;
  wire [8:0] stage1_acc0;
  (* src = "recursive_modules.v:261.29-261.40" *)
  output [8:0] stage1_acc1;
  wire [8:0] stage1_acc1;
  (* src = "recursive_modules.v:261.42-261.57" *)
  output [8:0] stage1_combined;
  wire [8:0] stage1_combined;
  assign _0_ = stage1_combined ^ (* src = "recursive_modules.v:289.21-289.54" *) stage0_combined;
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:264.21-274.6" *)
  dual_channel_l8 u_stage0 (
    .a0(in_a),
    .a1(in_b),
    .acc0(stage0_acc0),
    .acc1(stage0_acc1),
    .b0(in_b),
    .b1(in_a),
    .clk(clk),
    .combined(stage0_combined),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "recursive_modules.v:277.21-287.6" *)
  dual_channel_l8 u_stage1 (
    .a0(stage0_acc0[7:0]),
    .a1(stage0_acc1[7:0]),
    .acc0(stage1_acc0),
    .acc1(stage1_acc1),
    .b0(stage0_combined[7:0]),
    .b1(stage0_combined[7:0]),
    .clk(clk),
    .combined(stage1_combined),
    .rst(rst)
  );
  assign result = _0_;
endmodule
